import os

API_URL = os.environ.get('API_URL')
API_USER = os.environ.get('API_USER')
API_PASS = os.environ.get('API_PASS')

#
# DATASETS = [{'id': '1044', 'alias': 'WoRMS Porifera', 'title': 'World Porifera Database'},
#             {'id': '1058', 'alias': 'WoRMS Cumacea', 'title': 'World Cumacea Database'},
#             {'id': '1059', 'alias': 'WoRMS Ophiuroidea', 'title': 'World Ophiuroidea database'},
#             {'id': '1081', 'alias': 'WoRMS Bryozoa', 'title': 'World List of Bryozoa'},
#             {'id': '1085', 'alias': 'WoRMS Nemertea', 'title': 'World Nemertea Database'},
#             {'id': '1086', 'alias': 'WoRMS Bochusacea', 'title': 'World List of Bochusacea'},
#             {'id': '1087', 'alias': 'WoRMS Brachypoda', 'title': 'World List of Brachypoda'},
#             {'id': '1088', 'alias': 'WoRMS Mystacocarida', 'title': 'World List of Mystacocarida'},
#             {'id': '1090', 'alias': 'WoRMS Polychaeta', 'title': 'World Polychaeta database'},
#             {'id': '1091', 'alias': 'WoRMS Remipedia', 'title': 'World Remipedia Database'},
#             {'id': '1092', 'alias': 'WoRMS Tantulocarida', 'title': 'World List of Tantulocarida'},
#             {'id': '1093', 'alias': 'WoRMS Thermosbaenacea', 'title': 'World List of Thermosbaenacea'},
#             {'id': '1094', 'alias': 'WoRMS Isopoda', 'title': 'World Marine, Freshwater and Terrestrial Isopod Crustaceans database'},
#             {'id': '1095', 'alias': 'WoRMS Asteroidea', 'title': 'World Asteroidea Database'},
#             {'id': '1099', 'alias': 'WoRMS Oligochaeta', 'title': 'World List of Marine Oligochaeta'},
#             {'id': '1100', 'alias': 'WoRMS Xenoturbellida', 'title': 'World List of Xenoturbellida'},
#             {'id': '1103', 'alias': 'WoRMS Strepsiptera', 'title': 'Global Strepsiptera Database'},
#             {'id': '1105', 'alias': 'WoRMS Leptostraca', 'title': 'World List of Leptostraca'},
#             {'id': '1106', 'alias': 'WoRMS Echinoidea', 'title': 'World Echinoidea Database'},
#             {'id': '1107', 'alias': 'WoRMS Holothuroidea', 'title': 'World List of Holothuroidea'},
#             {'id': '1108', 'alias': 'WoRMS Brachyura', 'title': 'World List of marine Brachyura'},
#             {'id': '1109', 'alias': 'WoRMS Polycystina', 'title': 'World List of Polycystina (Radiolaria)'},
#             {'id': '1110', 'alias': 'WoRMS Tanaidacea', 'title': 'World List of Tanaidacea'},
#             {'id': '1112', 'alias': 'WoRMS Hydrozoa', 'title': 'World Hydrozoa Database'},
#             {'id': '1122', 'alias': 'WoRMS Gastrotricha', 'title': 'World Gastrotricha Database'},
#             {'id': '1123', 'alias': 'WoRMS Placozoa', 'title': 'World Placozoa Database'},
#             {'id': '1124', 'alias': 'WoRMS Priapulida', 'title': 'World List of Priapulida'},
#             {'id': '1125', 'alias': 'WoRMS Gnathostomulida', 'title': 'World List of Gnathostomulida'},
#             {'id': '1126', 'alias': 'WoRMS Monogenea', 'title': 'World List of Monogenea'},
#             {'id': '1127', 'alias': 'WoRMS Cestoda', 'title': 'World List of Cestoda'},
#             {'id': '1128', 'alias': 'WoRMS Trematoda', 'title': 'World List of Trematoda'},
#             {'id': '1129', 'alias': 'WoRMS Myxozoa', 'title': 'World list of Myxozoa'},
#             {'id': '1130', 'alias': 'WoRMS Mollusca', 'title': 'MolluscaBase'},
#             {'id': '1131', 'alias': 'WoRMS Octocorallia', 'title': 'World List of Octocorallia'},
#             {'id': '1132', 'alias': 'WoRMS Chaetognatha', 'title': 'World List of Chaetognatha'},
#             {'id': '1149', 'alias': 'WoRMS Orthonectida', 'title': 'World List of Orthonectida'},
#             {'id': '1150', 'alias': 'WoRMS Rhombozoa', 'title': 'World List of Rhombozoa'},
#             {'id': '1152', 'alias': 'WoRMS Merostomata', 'title': 'World List of Merostomata'},
#             {'id': '1153', 'alias': 'WoRMS Kinorhyncha', 'title': 'World List of Kinorhyncha'},
#             {'id': '1154', 'alias': 'WoRMS Cephalochordata', 'title': 'World List of Cephalochordata'},
#             {'id': '1157', 'alias': 'WoRMS Foraminifera', 'title': 'World Foraminifera Database'},
#             {'id': '1175', 'alias': 'WoRMS Ostracoda', 'title': 'World Ostracoda Database'},
#             {'id': '1176', 'alias': 'WoRMS Hexacoral', 'title': 'Hexacorallians (Actiniaria) of the World'},
#             {'id': '1178', 'alias': 'WoRMS Appendicularia', 'title': 'World List of Appendicularia'},
#             {'id': '1179', 'alias': 'WoRMS Ceriantharia', 'title': 'World list of Ceriantharia'},
#             {'id': '1180', 'alias': 'WoRMS Ctenophora', 'title': 'Phylum Ctenophora, a list of all valid species names harvested from the Internet between 1998 - pres'},
#             {'id': '1181', 'alias': 'WoRMS Cubozoa', 'title': 'World list of Cubozoa'},
#             {'id': '1182', 'alias': 'WoRMS Loricifera', 'title': 'World list of Loricifera'},
#             {'id': '1183', 'alias': 'WoRMS PycnoBase', 'title': 'World Pycnogonida Database'},
#             {'id': '1184', 'alias': 'WoRMS Staurozoa', 'title': 'World list of Staurozoa'},
#             {'id': '1185', 'alias': 'WoRMS Thaliacea', 'title': 'World list of Thaliacea'},
#             {'id': '1186', 'alias': 'WoRMS Ascidiacea', 'title': 'Ascidiacea World Database'},
#             {'id': '1188', 'alias': 'WoRMS Scyphozoa', 'title': 'World list of Scyphozoa'},
#             {'id': '1191', 'alias': 'WoRMS Copepoda', 'title': 'World of Copepods database'},
#             {'id': '1193', 'alias': 'WoRMS Turbellarians', 'title': 'World List of turbellarian worms (Acoelomorpha, Catenulida, Rhabditophora)'},
#             {'id': '1194', 'alias': 'WoRMS Antipatharia', 'title': 'World List of Antipatharia'},
#             {'id': '1195', 'alias': 'WoRMS Corallimorpharia', 'title': 'World List of Corallimorpharia'},
#             {'id': '1196', 'alias': 'WoRMS Scleractinia', 'title': 'World List of Scleractinia'},
#             {'id': '1197', 'alias': 'WoRMS Zoantharia', 'title': 'World List of Zoantharia'},
#             {'id': '1200', 'alias': 'WoRMS MilliBase', 'title': 'MilliBase'},
#             {'id': '1202', 'alias': 'WoRMS Amphipoda', 'title': 'World Amphipoda Database'},
#             {'id': '2299', 'alias': 'WoRMS Brachiopoda', 'title': 'Brachiopoda'},
#             {'id': '2300', 'alias': 'WoRMS Crinoidea', 'title': 'Crinoidea'},
#             {'id': '2301', 'alias': 'WoRMS Euphausiacea', 'title': 'Euphausiacea'},
#             {'id': '2302', 'alias': 'WoRMS Nemys', 'title': 'Nemys'},
# ]

DATASETS = [{'id': '1105', 'alias': 'WoRMS Leptostraca', 'title': 'World List of Leptostraca'},
            {'id': '1123', 'alias': 'WoRMS Placozoa', 'title': 'World Placozoa Database'},
            {'id': '1152', 'alias': 'WoRMS Merostomata', 'title': 'World List of Merostomata'},
            {'id': '1185', 'alias': 'WoRMS Thaliacea', 'title': 'World list of Thaliacea'},
]
